// chase/frontend/components/home/card_section.tsx
import React from "react";
import { useI18nContext } from "@/i18n/i18n-react";
import Card from "@components/home/card";
import { motion } from "framer-motion";

export default function CardSection() {
  const { LL } = useI18nContext();

  return (
    <>
      <div className="flex-1 flex flex-col lg:flex-row w-full justify-stretch p-8 gap-4">
        <Motion delay={0.2}>
          <Card
            src="/undraw/candidate.svg"
            alt="Debate"
            header={LL.home.heroCards.CARD_1_TITLE()}
            text={LL.home.heroCards.CARD_1_TEXT()}
          />
        </Motion>
        <Motion delay={0.4}>
          <Card
            src="/undraw/voting.svg"
            alt="Debate"
            header={LL.home.heroCards.CARD_2_TITLE()}
            text={LL.home.heroCards.CARD_2_TEXT()}
            comingSoonRibbon
          />
        </Motion>
        <Motion delay={0.6}>
          <Card
            src="/undraw/team_collaboration.svg"
            alt="Debate"
            header={LL.home.heroCards.CARD_3_TITLE()}
            text={LL.home.heroCards.CARD_3_TEXT()}
            comingSoonRibbon
          />
        </Motion>
      </div>
    </>
  );
}

function Motion({
  delay,
  children,
}: {
  delay: number;
  children: React.ReactNode;
}) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -10 }}
      transition={{
        duration: 1,
        type: "spring",
        delay: delay + 1,
        damping: 20,
        stiffness: 100,
      }}
      className="flex-1 relative"
    >
      {children}
    </motion.div>
  );
}

// src/routes/(pages)/CardSection.svelte
<script lang="ts">
import { fly } from "svelte/transition";
import candidate from "$assets/undraw/candidate.svg";
import teamCollaboration from "$assets/undraw/team_collaboration.svg";
import voting from "$assets/undraw/voting.svg";
import { m } from "$lib/paraglide/messages";
import Card from "./Card.svelte";
</script>

<div class="grid grid-cols-1 justify-stretch gap-4 p-4 md:grid-cols-3">
	<div in:fly={{ y: 10, duration: 1000, delay: 1000 }}>
		<Card
			src={candidate}
			alt="SpeakersList"
			header={m.homeHeroCardSpeakersListTitle()}
			text={m.homeHeroCardSpeakersListText()}
		/>
	</div>
	<div in:fly={{ y: 10, duration: 1000, delay: 1200 }}>
		<Card
			src={voting}
			alt="Voting"
			header={m.homeHeroCardVotingTitle()}
			text={m.homeHeroCardVotingText()}
		/>
	</div>
	<div in:fly={{ y: 10, duration: 1000, delay: 1400 }}>
		<Card
			src={teamCollaboration}
			alt="Resolution Editor"
			header={m.homeHeroCardResolutionEditorTitle()}
			text={m.homeHeroCardResolutionEditorText()}
			comingSoonRibbon
		/>
	</div>
</div>
