// chase/frontend/components/home/landing_hero.tsx
import React, { useState } from "react";
import { useI18nContext } from "@/i18n/i18n-react";
import Image from "next/image";
import { motion } from "framer-motion";

export default function LandingHero() {
  const { LL } = useI18nContext();

  const availableIllustrations = [
    "/undraw/the_world_is_mine.svg",
    "/undraw/world.svg",
    "/undraw/around_the_world.svg",
  ];

  const availableBlobs = [
    "/misc/blobs/blob_1.svg",
    "/misc/blobs/blob_2.svg",
    "/misc/blobs/blob_3.svg",
    "/misc/blobs/blob_4.svg",
    "/misc/blobs/blob_5.svg",
  ];

  const [illustration, _setIllustration] = useState(
    Math.floor(Math.random() * availableIllustrations.length),
  );
  const [blob, _setBlob] = useState(
    Math.floor(Math.random() * availableBlobs.length),
  );

  return (
    <>
      <div className="relative flex flex-col lg:flex-row items-center justify-center p-4 pt-52 pb-20 lg:pb-40 gap-5">
        <motion.div
          className="z-10"
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -10 }}
          transition={{
            duration: 1,
            type: "spring",
            delay: 0.2,
            damping: 20,
            stiffness: 100,
          }}
        >
          <Illustration
            availableIllustrations={availableIllustrations}
            chosenIllustration={illustration}
          />
        </motion.div>
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{
            duration: 0.5,
          }}
        >
          <Blob availableBlobs={availableBlobs} chosenBlob={blob} />
        </motion.div>
        <div className="flex flex-col items-center lg:items-end z-20 w-full lg:w-1/2 ">
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            transition={{
              duration: 1,
              type: "spring",
              delay: 0.7,
              damping: 20,
              stiffness: 100,
            }}
          >
            <h1 className="text-5xl lg:text-6xl font-bold font-serif text-center lg:text-right text-slate-900 mb-4 leading-tight">
              <span
                style={{
                  background: "linear-gradient(to right, #3d7dd2, #0000d0)",
                  backgroundClip: "text",
                  WebkitBackgroundClip: "text",
                  color: "transparent",
                }}
              >
                MUN
              </span>
              {LL.home.CAPTION()}
            </h1>
          </motion.div>
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{
              duration: 1.5,
              delay: 1,
            }}
          >
            <h2 className="text-xl lg:text-2xl text-center lg:text-right text-slate-900 leading-normal">
              {LL.home.HERO_TEXT()}
            </h2>
          </motion.div>
        </div>
      </div>
    </>
  );
}

interface IllustrationProps {
  availableIllustrations: string[];
  chosenIllustration: number;
}

const Illustration = ({
  availableIllustrations,
  chosenIllustration,
}: IllustrationProps) => {
  return (
    <>
      <Image
        src={availableIllustrations[chosenIllustration]}
        alt="Logo"
        width={500}
        height={128}
      />
    </>
  );
};

interface BlobProps {
  availableBlobs: string[];
  chosenBlob: number;
}

const Blob = ({ availableBlobs, chosenBlob }: BlobProps) => {
  return (
    <>
      <Image
        src={availableBlobs[chosenBlob]}
        alt="Logo"
        width={800}
        height={128}
        className="absolute top-24 md:top-0 lg:top-0 left-0 z-0"
      />
    </>
  );
};

// src/routes/(pages)/LandingHero.svelte
<script lang="ts">
import { fade, fly } from "svelte/transition";
import blob1 from "$lib/assets/misc/blobs/blob_1.svg";
import blob2 from "$lib/assets/misc/blobs/blob_2.svg";
import blob3 from "$lib/assets/misc/blobs/blob_3.svg";
import blob4 from "$lib/assets/misc/blobs/blob_4.svg";
import blob5 from "$lib/assets/misc/blobs/blob_5.svg";
import aroundTheWorld from "$lib/assets/undraw/around_the_world.svg";
import theWorldIsMine from "$lib/assets/undraw/the_world_is_mine.svg";
import world from "$lib/assets/undraw/world.svg";
import { m } from "$lib/paraglide/messages";

const availableIllustrations = [theWorldIsMine, world, aroundTheWorld];
const availableBlobs = [blob1, blob2, blob3, blob4, blob5];

const illustration = $state(
	Math.floor(Math.random() * availableIllustrations.length),
);
const blob = $state(Math.floor(Math.random() * availableBlobs.length));
</script>

<div
	class="relative flex flex-col items-center justify-center gap-5 p-4 pb-20 pt-52 lg:flex-row lg:pb-40"
>
	<div class="z-10" in:fly={{ y: 10, duration: 1000, delay: 200 }}>
		<img src={availableIllustrations[illustration]} alt="Logo" width="500" height="128" />
	</div>
	<div in:fade={{ duration: 500 }}>
		<img
			src={availableBlobs[blob]}
			alt="Blob"
			width="800"
			height="128"
			class="absolute left-0 top-24 z-0 md:top-0 lg:top-0"
		/>
	</div>
	<div class="z-20 flex w-full flex-col items-center lg:w-1/2 lg:items-end">
		<div in:fly={{ y: 10, duration: 1000, delay: 700 }}>
			<h1
				class="mb-4 text-center font-serif text-5xl font-bold leading-tight text-slate-900 lg:text-right lg:text-6xl dark:text-white"
			>
				<span
					style="background: linear-gradient(to right, #3d7dd2, #0000d0); background-clip: text; -webkit-background-clip: text; color: transparent;"
				>
					MUN
				</span>
				{m.homeCaption()}
			</h1>
		</div>
		<div in:fade={{ duration: 1500, delay: 1000 }}>
			<h2
				class="text-center text-xl leading-normal text-slate-900 lg:text-right lg:text-2xl dark:text-white"
			>
				{m.homeHeroText()}
			</h2>
		</div>
	</div>
</div>
