// src/routes/(pages)/Card.svelte
<script lang="ts">
import ComingSoonRibbon from "./ComingSoonRibbon.svelte";

interface Props {
	src: string;
	alt: string;
	header: string;
	text: string;
	comingSoonRibbon?: boolean;
}

const { src, alt, header, text, comingSoonRibbon = false }: Props = $props();
</script>

<div class="card bg-base-100 relative h-full flex-1 shadow-sm">
	<div class="card-header flex h-60 items-center justify-center p-8">
		<img {src} {alt} />
	</div>
	<div class="card-body">
		<h2 class="mb-4 text-center font-serif text-3xl font-bold">
			{header}
		</h2>
		<p class="text-md text-center">{text}</p>
	</div>
	{#if comingSoonRibbon}
		<ComingSoonRibbon />
	{/if}
</div>

// chase/frontend/components/home/card.tsx
import React from "react";
import { useI18nContext } from "@/i18n/i18n-react";
import Image from "next/image";

type CardProps = {
  src: string;
  alt: string;
  header: string;
  text: string;
};

export default function Card({ src, alt, header, text }: CardProps) {
  const { LL } = useI18nContext();

  return (
    <>
      <div className="flex-1 flex flex-col justify-center items-center bg-white p-8 rounded-xl shadow-sm">
        <Image
          src={src}
          alt={alt}
          width={400}
          height={400}
          className="mb-10 h-40"
        />
        <h2
          className="text-3xl text-center font-bold mb-4"
          style={{ fontFamily: "Vollkorn" }}
        >
          {header}
        </h2>
        <p className="text-md text-center">{text}</p>
      </div>
    </>
  );
}
