// src/routes/(pages)/TextSection.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	interface Props {
		title: string;
		text: string;
		children?: Snippet;
	}

	let { title, text, children }: Props = $props();
</script>

<h1
	class="text-center font-serif text-3xl leading-tight font-bold text-slate-900 lg:text-right lg:text-4xl dark:text-white"
>
	{title}
</h1>
<div class="pb-10 lg:pb-0 flex flex-col items-center lg:items-start">
	<p
		class="text-md text-center leading-normal text-slate-900 lg:text-left lg:text-lg dark:text-white"
	>
		{text}
	</p>
	{#if children}
		{@render children()}
	{/if}
</div>

// chase/frontend/components/home/text_section.tsx
import React from "react";
import Button from "../button";
import { useRouter } from "next/navigation";

type TextSectionProps = {
  title: string;
  text: string;
  button?: {
    lable: string;
    link?: string;
    onClick?: () => void;
    faIcon: string;
  };
};

export default function TextSection({ title, text, button }: TextSectionProps) {
  const Router = useRouter();

  return (
    <>
      <h1 className="text-3xl lg:text-4xl font-bold font-serif text-center lg:text-right text-slate-900 leading-tight">
        {title}
      </h1>
      <div className="pb-10 lg:pb-0">
        <p className="text-md lg:text-lg text-center lg:text-left text-slate-900 leading-normal">
          {text}
        </p>
        {button && (
          <div className="pt-4 flex justify-center lg:justify-start">
            <Button
              label={button.lable}
              onClick={() => {
                if (button.onClick) {
                  button.onClick();
                  return;
                }
                if (button.link) {
                  Router.push(button.link);
                  return;
                }
                throw new Error("No link or onClick function provided");
              }}
              faIcon={button.faIcon}
              className="mt-4"
            />
          </div>
        )}
      </div>
    </>
  );
}
